"""Build taxonomy.json — the canonical philosopher/concept index (v0).

Reading agents map chapters to these slugs; anything unmappable is logged
as a hole and later merged back in as a taxonomy extension.
"""
import json
from pathlib import Path

OUT = Path(r"B:\ai_philosophy\sratchpad\popcult_index\taxonomy.json").resolve()

DOMAINS = {
    "ancient": "Ancient Greek & Hellenistic Philosophy",
    "eastern-world": "Eastern & World Philosophy",
    "medieval-early-modern": "Medieval & Early Modern Philosophy",
    "kant-german-idealism": "Kant & German Idealism",
    "nineteenth-century": "19th Century: Nietzsche, Marx & After",
    "utilitarian-consequentialist": "Utilitarianism & Consequentialism",
    "existentialism-phenomenology": "Existentialism & Phenomenology",
    "mind-language-metaphysics": "Mind, Language & Metaphysics",
    "knowledge-science-reality": "Knowledge, Science & Reality",
    "ethics-moral-psychology": "Ethics & Moral Psychology",
    "political-social": "Political & Social Philosophy",
    "pragmatism-american": "Pragmatism & American Philosophy",
    "feminism-gender-race": "Feminist, Gender & Race Philosophy",
    "environment-animal": "Environmental & Animal Ethics",
    "religion-meaning": "God, Faith & the Meaning of Life",
}

# slug: [Name, dates, domain]
P = {
    # ancient
    "socrates": ["Socrates", "470–399 BC", "ancient"],
    "plato": ["Plato", "428–348 BC", "ancient"],
    "aristotle": ["Aristotle", "384–322 BC", "ancient"],
    "heraclitus": ["Heraclitus", "c. 535–475 BC", "ancient"],
    "parmenides": ["Parmenides", "c. 515–450 BC", "ancient"],
    "zeno-elea": ["Zeno of Elea", "c. 490–430 BC", "ancient"],
    "democritus": ["Democritus", "c. 460–370 BC", "ancient"],
    "pythagoras": ["Pythagoras", "c. 570–495 BC", "ancient"],
    "protagoras": ["Protagoras", "c. 490–420 BC", "ancient"],
    "diogenes-cynic": ["Diogenes the Cynic", "c. 412–323 BC", "ancient"],
    "plutarch": ["Plutarch", "c. 46–119 AD", "ancient"],
    "epicurus": ["Epicurus", "341–270 BC", "ancient"],
    "pyrrho": ["Pyrrho", "c. 360–270 BC", "ancient"],
    "sextus-empiricus": ["Sextus Empiricus", "c. 160–210 AD", "ancient"],
    "zeno-citium": ["Zeno of Citium", "c. 334–262 BC", "ancient"],
    "epictetus": ["Epictetus", "c. 50–135 AD", "ancient"],
    "seneca": ["Seneca", "c. 4 BC–65 AD", "ancient"],
    "marcus-aurelius": ["Marcus Aurelius", "121–180 AD", "ancient"],
    "cicero": ["Cicero", "106–43 BC", "ancient"],
    "lucretius": ["Lucretius", "c. 99–55 BC", "ancient"],
    "plotinus": ["Plotinus", "c. 204–270 AD", "ancient"],
    # eastern-world
    "confucius": ["Confucius", "551–479 BC", "eastern-world"],
    "mencius": ["Mencius", "372–289 BC", "eastern-world"],
    "xunzi": ["Xunzi", "c. 310–235 BC", "eastern-world"],
    "laozi": ["Laozi", "6th c. BC", "eastern-world"],
    "zhuangzi": ["Zhuangzi", "c. 369–286 BC", "eastern-world"],
    "sun-tzu": ["Sun Tzu", "5th c. BC", "eastern-world"],
    "buddha": ["The Buddha", "c. 563–483 BC", "eastern-world"],
    "nagarjuna": ["Nagarjuna", "c. 150–250 AD", "eastern-world"],
    "dogen": ["Dogen", "1200–1253", "eastern-world"],
    "shankara": ["Shankara", "c. 700–750 AD", "eastern-world"],
    "gandhi": ["Mahatma Gandhi", "1869–1948", "eastern-world"],
    # medieval-early-modern
    "augustine": ["Augustine of Hippo", "354–430", "medieval-early-modern"],
    "boethius": ["Boethius", "c. 477–524", "medieval-early-modern"],
    "anselm": ["Anselm of Canterbury", "1033–1109", "medieval-early-modern"],
    "aquinas": ["Thomas Aquinas", "1225–1274", "medieval-early-modern"],
    "ockham": ["William of Ockham", "c. 1287–1347", "medieval-early-modern"],
    "maimonides": ["Maimonides", "1138–1204", "medieval-early-modern"],
    "avicenna": ["Avicenna (Ibn Sina)", "980–1037", "medieval-early-modern"],
    "averroes": ["Averroes (Ibn Rushd)", "1126–1198", "medieval-early-modern"],
    "al-ghazali": ["Al-Ghazali", "c. 1058–1111", "medieval-early-modern"],
    "descartes": ["René Descartes", "1596–1650", "medieval-early-modern"],
    "spinoza": ["Baruch Spinoza", "1632–1677", "medieval-early-modern"],
    "leibniz": ["Gottfried Leibniz", "1646–1716", "medieval-early-modern"],
    "pascal": ["Blaise Pascal", "1623–1662", "medieval-early-modern"],
    "montaigne": ["Michel de Montaigne", "1533–1592", "medieval-early-modern"],
    "locke": ["John Locke", "1632–1704", "medieval-early-modern"],
    "berkeley": ["George Berkeley", "1685–1753", "medieval-early-modern"],
    "hume": ["David Hume", "1711–1776", "medieval-early-modern"],
    "reid": ["Thomas Reid", "1710–1796", "medieval-early-modern"],
    # kant-german-idealism
    "kant": ["Immanuel Kant", "1724–1804", "kant-german-idealism"],
    "fichte": ["Johann Fichte", "1762–1814", "kant-german-idealism"],
    "hegel": ["G.W.F. Hegel", "1770–1831", "kant-german-idealism"],
    "schopenhauer": ["Arthur Schopenhauer", "1788–1860", "kant-german-idealism"],
    # nineteenth-century
    "nietzsche": ["Friedrich Nietzsche", "1844–1900", "nineteenth-century"],
    "marx": ["Karl Marx", "1818–1883", "nineteenth-century"],
    "spencer": ["Herbert Spencer", "1820–1903", "nineteenth-century"],
    "kirkegaard-19c": ["—", "", "nineteenth-century"],  # placeholder removed below
    # utilitarian-consequentialist
    "bentham": ["Jeremy Bentham", "1748–1832", "utilitarian-consequentialist"],
    "mill": ["John Stuart Mill", "1806–1873", "utilitarian-consequentialist"],
    "sidgwick": ["Henry Sidgwick", "1838–1900", "utilitarian-consequentialist"],
    "singer": ["Peter Singer", "b. 1946", "utilitarian-consequentialist"],
    # existentialism-phenomenology
    "kierkegaard": ["Søren Kierkegaard", "1813–1855", "existentialism-phenomenology"],
    "husserl": ["Edmund Husserl", "1859–1938", "existentialism-phenomenology"],
    "heidegger": ["Martin Heidegger", "1889–1976", "existentialism-phenomenology"],
    "sartre": ["Jean-Paul Sartre", "1905–1980", "existentialism-phenomenology"],
    "beauvoir": ["Simone de Beauvoir", "1908–1986", "existentialism-phenomenology"],
    "camus": ["Albert Camus", "1913–1960", "existentialism-phenomenology"],
    "merleau-ponty": ["Maurice Merleau-Ponty", "1908–1961", "existentialism-phenomenology"],
    "frankl": ["Viktor Frankl", "1905–1997", "existentialism-phenomenology"],
    "levinas": ["Emmanuel Levinas", "1906–1995", "existentialism-phenomenology"],
    # mind-language-metaphysics
    "turing": ["Alan Turing", "1912–1954", "mind-language-metaphysics"],
    "searle": ["John Searle", "b. 1932", "mind-language-metaphysics"],
    "putnam": ["Hilary Putnam", "1926–2016", "mind-language-metaphysics"],
    "chalmers": ["David Chalmers", "b. 1966", "mind-language-metaphysics"],
    "dennett": ["Daniel Dennett", "1942–2024", "mind-language-metaphysics"],
    "wittgenstein": ["Ludwig Wittgenstein", "1889–1951", "mind-language-metaphysics"],
    "russell": ["Bertrand Russell", "1872–1970", "mind-language-metaphysics"],
    "moore": ["G.E. Moore", "1873–1958", "mind-language-metaphysics"],
    "frege": ["Gottlob Frege", "1848–1925", "mind-language-metaphysics"],
    "quine": ["W.V.O. Quine", "1908–2000", "mind-language-metaphysics"],
    "kripke": ["Saul Kripke", "1940–2022", "mind-language-metaphysics"],
    "lewis": ["David Lewis", "1941–2001", "mind-language-metaphysics"],
    "ryle": ["Gilbert Ryle", "1900–1976", "mind-language-metaphysics"],
    "jackson": ["Frank Jackson", "b. 1943", "mind-language-metaphysics"],
    "nagel": ["Thomas Nagel", "b. 1937", "mind-language-metaphysics"],
    "parfit": ["Derek Parfit", "1942–2017", "mind-language-metaphysics"],
    "mctaggart": ["J.M.E. McTaggart", "1866–1925", "mind-language-metaphysics"],
    "clark": ["Andy Clark", "b. 1957", "mind-language-metaphysics"],
    "vann-inwagen": ["Peter van Inwagen", "b. 1942", "mind-language-metaphysics"],
    "bergson": ["Henri Bergson", "1859–1941", "mind-language-metaphysics"],
    "freud": ["Sigmund Freud", "1856–1939", "mind-language-metaphysics"],
    "jung": ["Carl Jung", "1875–1961", "mind-language-metaphysics"],
    "lacan": ["Jacques Lacan", "1901–1981", "mind-language-metaphysics"],
    "isaiah-berlin": ["Isaiah Berlin", "1909–1997", "political-social"],
    "gadamer": ["Hans-Georg Gadamer", "1900–2002", "existentialism-phenomenology"],
    # knowledge-science-reality
    "gettier": ["Edmund Gettier", "1927–2021", "knowledge-science-reality"],
    "goldman": ["Alvin Goldman", "b. 1938", "knowledge-science-reality"],
    "kuhn": ["Thomas Kuhn", "1922–1996", "knowledge-science-reality"],
    "popper": ["Karl Popper", "1902–1994", "knowledge-science-reality"],
    "feyerabend": ["Paul Feyerabend", "1924–1994", "knowledge-science-reality"],
    "bacon": ["Francis Bacon", "1561–1626", "knowledge-science-reality"],
    "bostrom": ["Nick Bostrom", "b. 1973", "knowledge-science-reality"],
    # ethics-moral-psychology
    "foot": ["Philippa Foot", "1920–2010", "ethics-moral-psychology"],
    "thomson": ["Judith Jarvis Thomson", "1929–2020", "ethics-moral-psychology"],
    "rachels": ["James Rachels", "1941–2003", "ethics-moral-psychology"],
    "mackie": ["J.L. Mackie", "1917–1981", "ethics-moral-psychology"],
    "williams": ["Bernard Williams", "1929–2003", "ethics-moral-psychology"],
    "frankfurt": ["Harry Frankfurt", "1929–2023", "ethics-moral-psychology"],
    "korsgaard": ["Christine Korsgaard", "b. 1952", "ethics-moral-psychology"],
    "gilligan": ["Carol Gilligan", "b. 1936", "ethics-moral-psychology"],
    "noddings": ["Nel Noddings", "1929–2022", "ethics-moral-psychology"],
    "macintyre": ["Alasdair MacIntyre", "b. 1929", "ethics-moral-psychology"],
    "nussbaum": ["Martha Nussbaum", "b. 1947", "ethics-moral-psychology"],
    "anscombe": ["Elizabeth Anscombe", "1919–2001", "ethics-moral-psychology"],
    "adam-smith": ["Adam Smith", "1723–1790", "ethics-moral-psychology"],
    "wolf": ["Susan Wolf", "b. 1952", "ethics-moral-psychology"],
    # political-social
    "hobbes": ["Thomas Hobbes", "1588–1679", "political-social"],
    "rousseau": ["Jean-Jacques Rousseau", "1712–1778", "political-social"],
    "machiavelli": ["Niccolò Machiavelli", "1469–1527", "political-social"],
    "rawls": ["John Rawls", "1921–2002", "political-social"],
    "nozick": ["Robert Nozick", "1938–2002", "political-social"],
    "sandel": ["Michael Sandel", "b. 1953", "political-social"],
    "walzer": ["Michael Walzer", "b. 1935", "political-social"],
    "arendt": ["Hannah Arendt", "1906–1975", "political-social"],
    "foucault": ["Michel Foucault", "1926–1984", "political-social"],
    "derrida": ["Jacques Derrida", "1930–2004", "political-social"],
    "deleuze": ["Gilles Deleuze", "1925–1995", "political-social"],
    "baudrillard": ["Jean Baudrillard", "1929–2007", "political-social"],
    "lyotard": ["Jean-François Lyotard", "1924–1998", "political-social"],
    "gramsci": ["Antonio Gramsci", "1891–1937", "political-social"],
    "marcuse": ["Herbert Marcuse", "1898–1979", "political-social"],
    "adorno": ["Theodor Adorno", "1903–1969", "political-social"],
    "benjamin": ["Walter Benjamin", "1892–1940", "political-social"],
    "habermas": ["Jürgen Habermas", "b. 1929", "political-social"],
    # pragmatism-american
    "peirce": ["Charles Sanders Peirce", "1839–1914", "pragmatism-american"],
    "william-james": ["William James", "1842–1910", "pragmatism-american"],
    "dewey": ["John Dewey", "1859–1952", "pragmatism-american"],
    "rorty": ["Richard Rorty", "1931–2007", "pragmatism-american"],
    "addams": ["Jane Addams", "1860–1935", "pragmatism-american"],
    "emerson": ["Ralph Waldo Emerson", "1803–1882", "pragmatism-american"],
    "thoreau": ["Henry David Thoreau", "1817–1862", "pragmatism-american"],
    # feminism-gender-race
    "wollstonecraft": ["Mary Wollstonecraft", "1759–1797", "feminism-gender-race"],
    "friedan": ["Betty Friedan", "1921–2006", "feminism-gender-race"],
    "firestone": ["Shulamith Firestone", "1945–2012", "feminism-gender-race"],
    "butler": ["Judith Butler", "b. 1956", "feminism-gender-race"],
    "hooks": ["bell hooks", "1952–2021", "feminism-gender-race"],
    "mackinnon": ["Catharine MacKinnon", "b. 1946", "feminism-gender-race"],
    "frye": ["Marilyn Frye", "b. 1941", "feminism-gender-race"],
    "young": ["Iris Marion Young", "1949–2006", "feminism-gender-race"],
    "crenshaw": ["Kimberlé Crenshaw", "b. 1959", "feminism-gender-race"],
    "dubois": ["W.E.B. Du Bois", "1868–1963", "feminism-gender-race"],
    "mills": ["Charles W. Mills", "1951–2021", "feminism-gender-race"],
    "fanon": ["Frantz Fanon", "1925–1961", "feminism-gender-race"],
    "appiah": ["Kwame Anthony Appiah", "b. 1954", "feminism-gender-race"],
    "fricker": ["Miranda Fricker", "b. 1966", "feminism-gender-race"],
    "cornel-west": ["Cornel West", "b. 1953", "feminism-gender-race"],
    # environment-animal
    "leopold": ["Aldo Leopold", "1887–1948", "environment-animal"],
    "naess": ["Arne Naess", "1912–2009", "environment-animal"],
    "plumwood": ["Val Plumwood", "1939–2008", "environment-animal"],
    "warren": ["Karen J. Warren", "b. 1947", "environment-animal"],
    "regan": ["Tom Regan", "1938–2017", "environment-animal"],
    # religion-meaning
    "paley": ["William Paley", "1743–1805", "religion-meaning"],
    "plantinga": ["Alvin Plantinga", "b. 1932", "religion-meaning"],
    "tillich": ["Paul Tillich", "1886–1965", "religion-meaning"],
    "buber": ["Martin Buber", "1878–1965", "religion-meaning"],
    "kierkeg": ["—", "", "religion-meaning"],  # placeholder removed below
    # hole-driven extensions (final aggregation, 2026-09-28): 67 philosophers
    "cs-lewis": ["C.S. Lewis", "", "religion-meaning"],
    "ayn-rand": ["Ayn Rand", "", "political-social"],
    "charles-taylor": ["Charles Taylor", "", "political-social"],
    "bakhtin": ["Mikhail Bakhtin", "", "political-social"],
    "max-weber": ["Max Weber", "", "political-social"],
    "voltaire": ["Voltaire", "", "medieval-early-modern"],
    "zizek": ["Slavoj Žižek", "", "political-social"],
    "kristeva": ["Julia Kristeva", "", "mind-language-metaphysics"],
    "donald-davidson": ["Donald Davidson", "", "mind-language-metaphysics"],
    "whitehead": ["Alfred North Whitehead", "", "pragmatism-american"],
    "george-herbert-mead": ["George Herbert Mead", "", "pragmatism-american"],
    "haraway": ["Donna Haraway", "", "feminism-gender-race"],
    "schelling": ["F.W.J. Schelling", "", "kant-german-idealism"],
    "john-hick": ["John Hick", "", "religion-meaning"],
    "langer": ["Susanne Langer", "", "mind-language-metaphysics"],
    "becker-denial-of-death": ["Ernest Becker", "", "existentialism-phenomenology"],
    "carroll-aesthetics": ["Noël Carroll", "", "mind-language-metaphysics"],
    "warren-personhood": ["Mary Anne Warren", "", "ethics-moral-psychology"],
    "roland-barthes": ["Roland Barthes", "", "political-social"],
    "clifford": ["W.K. Clifford", "", "knowledge-science-reality"],
    "bourdieu": ["Pierre Bourdieu", "", "political-social"],
    "richard-taylor": ["Richard Taylor", "", "mind-language-metaphysics"],
    "dostoevsky": ["Fyodor Dostoevsky", "", "nineteenth-century"],
    "paulo-freire": ["Paulo Freire", "", "political-social"],
    "annette-baier": ["Annette Baier", "", "ethics-moral-psychology"],
    "melanie-klein": ["Melanie Klein", "", "mind-language-metaphysics"],
    "galen-strawson": ["Galen Strawson", "", "mind-language-metaphysics"],
    "carl-schmitt": ["Carl Schmitt", "", "political-social"],
    "vico": ["Giambattista Vico", "", "medieval-early-modern"],
    "empedocles": ["Empedocles", "", "ancient"],
    "edmund-burke": ["Edmund Burke", "", "medieval-early-modern"],
    "clausewitz": ["Carl von Clausewitz", "", "political-social"],
    "darwin": ["Charles Darwin", "", "knowledge-science-reality"],
    "mcluhan": ["Marshall McLuhan", "", "political-social"],
    "derrick-bell": ["Derrick Bell", "", "feminism-gender-race"],
    "cavell": ["Stanley Cavell", "", "pragmatism-american"],
    "joseph-campbell": ["Joseph Campbell", "", "religion-meaning"],
    "horkheimer": ["Max Horkheimer", "", "political-social"],
    "j-l-austin": ["J.L. Austin", "", "mind-language-metaphysics"],
    "rudolf-carnap": ["Rudolf Carnap", "", "mind-language-metaphysics"],
    "tocqueville": ["Alexis de Tocqueville", "", "political-social"],
    "tolstoy": ["Leo Tolstoy", "", "political-social"],
    "giorgio-agamben": ["Giorgio Agamben", "", "political-social"],
    "milton-friedman": ["Milton Friedman", "", "political-social"],
    "josiah-royce": ["Josiah Royce", "", "pragmatism-american"],
    "goffman": ["Erving Goffman", "", "political-social"],
    "graham-priest": ["Graham Priest", "", "mind-language-metaphysics"],
    "gaston-bachelard": ["Gaston Bachelard", "", "existentialism-phenomenology"],
    "georges-bataille": ["Georges Bataille", "", "political-social"],
    "iris-murdoch": ["Iris Murdoch", "", "ethics-moral-psychology"],
    "simone-weil": ["Simone Weil", "", "religion-meaning"],
    "max-scheler": ["Max Scheler", "", "existentialism-phenomenology"],
    "benatar": ["David Benatar", "", "ethics-moral-psychology"],
    "hierocles": ["Hierocles", "", "ancient"],
    "kropotkin": ["Pyotr Kropotkin", "", "political-social"],
    "girard": ["René Girard", "", "ethics-moral-psychology"],
    "audre-lorde": ["Audre Lorde", "", "feminism-gender-race"],
    "kendall-walton": ["Kendall Walton", "", "mind-language-metaphysics"],
    "irigaray": ["Luce Irigaray", "", "feminism-gender-race"],
    "byung-chul-han": ["Byung-Chul Han", "", "political-social"],
    "jameson": ["Fredric Jameson", "", "political-social"],
    "umberto-eco": ["Umberto Eco", "", "political-social"],
    "huizinga": ["Johan Huizinga", "", "mind-language-metaphysics"],
    "bernard-suits": ["Bernard Suits", "", "ethics-moral-psychology"],
    "p-f-strawson": ["P.F. Strawson", "", "ethics-moral-psychology"],
    "h-richard-niebuhr": ["H. Richard Niebuhr", "", "religion-meaning"],
    "guy-debord": ["Guy Debord", "", "political-social"],
}

# 2026-10-03 extension: holes from the 6 newly recovered books (u439-u449)
P["panini"] = ["Panini", "c. 4th c. BCE", "eastern-world"]
P["ramanuja"] = ["Ramanuja", "1017–1137", "eastern-world"]
P["arthur-danto"] = ["Arthur Danto", "1924–2013", "mind-language-metaphysics"]
P["linda-zagzebski"] = ["Linda Zagzebski", "", "ethics-moral-psychology"]
P["heather-widdows"] = ["Heather Widdows", "", "feminism-gender-race"]
P["paul-ricoeur"] = ["Paul Ricoeur", "1913–2005", "mind-language-metaphysics"]
P["michael-cholbi"] = ["Michael Cholbi", "", "ethics-moral-psychology"]
P["edith-stein"] = ["Edith Stein", "1891–1942", "mind-language-metaphysics"]
P["w-d-ross"] = ["W. D. Ross", "1877–1971", "ethics-moral-psychology"]
P["peter-geach"] = ["Peter Geach", "1916–2013", "ethics-moral-psychology"]
P["helene-cixous"] = ["Hélène Cixous", "1937–", "feminism-gender-race"]
P["ibram-x-kendi"] = ["Ibram X. Kendi", "1982–", "feminism-gender-race"]
P["reinhold-niebuhr"] = ["Reinhold Niebuhr", "1892–1971", "political-social"]
P["axel-honneth"] = ["Axel Honneth", "1949–", "political-social"]
P["thomas-paine"] = ["Thomas Paine", "1737–1809", "political-social"]
P["ruth-benedict"] = ["Ruth Benedict", "1887–1948", "ethics-moral-psychology"]
P["malinowski"] = ["Bronisław Malinowski", "1884–1942", "knowledge-science-reality"]
P["graham-greene"] = ["Graham Greene", "1904–1991", "religion-meaning"]
P["linda-hutcheon"] = ["Linda Hutcheon", "", "mind-language-metaphysics"]

del P["kirkegaard-19c"]
del P["kierkeg"]

# slug: [Name, philosopher-or-"" (school-level), domain-if-no-philosopher]
C = {
    # ancient
    "socratic-method": ["Socratic Method (elenchus)", "socrates"],
    "socratic-ignorance": ["Socratic Ignorance (knowing that you don't know)", "socrates"],
    "unexamined-life": ["The Unexamined Life", "socrates"],
    "plato-forms": ["Theory of Forms", "plato"],
    "plato-cave": ["Allegory of the Cave", "plato"],
    "plato-ring-of-gyges": ["Ring of Gyges (why be moral?)", "plato"],
    "plato-justice": ["Justice in the Republic", "plato"],
    "philosopher-king": ["The Philosopher King", "plato"],
    "plato-tripartite-soul": ["Tripartite Soul", "plato"],
    "platonic-love": ["Platonic Love (the ladder of love)", "plato"],
    "noble-lie": ["The Noble Lie", "plato"],
    "plato-euthyphro": ["Euthyphro Dilemma", "plato"],
    "aristotle-virtue-ethics": ["Virtue Ethics (arete)", "aristotle"],
    "aristotle-golden-mean": ["The Golden Mean", "aristotle"],
    "aristotle-eudaimonia": ["Eudaimonia (flourishing)", "aristotle"],
    "aristotle-four-causes": ["The Four Causes", "aristotle"],
    "aristotle-soul": ["Aristotle on the Soul", "aristotle"],
    "aristotle-friendship": ["Aristotle on Friendship (philia)", "aristotle"],
    "aristotle-potentiality": ["Potentiality and Actuality", "aristotle"],
    "political-animal": ["Man as Political Animal", "aristotle"],
    "aristotle-practical-wisdom": ["Practical Wisdom (phronesis)", "aristotle"],
    "heraclitean-flux": ["Everything Flows / Logos", "heraclitus"],
    "parmenidean-being": ["Being and Changelessness", "parmenides"],
    "zeno-paradoxes": ["Zeno's Paradoxes", "zeno-elea"],
    "atomism": ["Atomism", "democritus"],
    "pythagorean-harmony": ["Pythagorean Harmony of the Spheres", "pythagoras"],
    "sophist-relativism": ["Man Is the Measure (sophistic relativism)", "protagoras"],
    "cynicism": ["Cynicism (living according to nature)", "diogenes-cynic"],
    "ship-of-theseus": ["Ship of Theseus", "plutarch"],
    "epicurean-pleasure": ["Epicurean Pleasure (ataraxia)", "epicurus"],
    "epicurean-death": ["Death Is Nothing to Us", "epicurus"],
    "pyrrhonian-skepticism": ["Pyrrhonian Skepticism (suspension of judgment)", "pyrrho"],
    "stoicism": ["Stoicism", "", "ancient"],
    "dichotomy-of-control": ["The Dichotomy of Control", "epictetus"],
    "stoic-indifferents": ["Preferred Indifferents", "epictetus"],
    "stoic-cosmopolitanism": ["Stoic Cosmopolitanism (citizens of the world)", "seneca"],
    "stoic-premeditation": ["Premeditatio Malorum", "seneca"],
    "stoic-view-from-above": ["The View from Above", "marcus-aurelius"],
    "stoic-present-moment": ["Living in the Present", "marcus-aurelius"],
    "cicero-duty": ["Ciceronian Duty (de Officiis)", "cicero"],
    "lucretian-nature": ["On the Nature of Things", "lucretius"],
    "neoplatonism": ["Neoplatonism (the One)", "plotinus"],
    # eastern-world
    "confucian-ren": ["Ren (benevolence/humaneness)", "confucius"],
    "confucian-li": ["Li (ritual propriety)", "confucius"],
    "confucian-filiality": ["Xiao (filial piety)", "confucius"],
    "confucian-junzi": ["The Junzi (exemplary person)", "confucius"],
    "rectification-of-names": ["Rectification of Names", "confucius"],
    "mencius-good-nature": ["Human Nature Is Good", "mencius"],
    "xunzi-bad-nature": ["Human Nature Is Bad (and needs ritual)", "xunzi"],
    "taoism": ["Taoism (Daoism)", "", "eastern-world"],
    "the-tao": ["The Tao (the Way)", "laozi"],
    "wu-wei": ["Wu Wei (effortless action)", "laozi"],
    "zhuangzi-perspectivism": ["Zhuangzi's Perspectivism (butterfly dream)", "zhuangzi"],
    "yin-yang": ["Yin and Yang", "", "eastern-world"],
    "sun-tzu-strategy": ["Strategy Without Conflict", "sun-tzu"],
    "buddhism": ["Buddhism", "", "eastern-world"],
    "four-noble-truths": ["The Four Noble Truths", "buddha"],
    "buddhist-impermanence": ["Impermanence (anicca)", "buddha"],
    "buddhist-non-self": ["Non-Self (anatman)", "buddha"],
    "buddhist-karma": ["Karma and Rebirth", "buddha"],
    "buddhist-compassion": ["Compassion (karuna)", "buddha"],
    "nagarjuna-emptiness": ["Emptiness (sunyata)", "nagarjuna"],
    "zen": ["Zen Buddhism", "", "eastern-world"],
    "atman-brahman": ["Atman and Brahman", "shankara"],
    "dharma": ["Dharma", "", "eastern-world"],
    "ahimsa": ["Ahimsa (nonviolence)", "gandhi"],
    # medieval-early-modern
    "augustine-city-of-god": ["The Two Cities", "augustine"],
    "augustine-time": ["Augustine on Time", "augustine"],
    "augustine-will": ["The Divided Will", "augustine"],
    "wheel-of-fortune": ["The Wheel of Fortune", "boethius"],
    "boethius-consolation": ["The Consolation of Philosophy", "boethius"],
    "ontological-argument": ["The Ontological Argument", "anselm"],
    "aquinas-natural-law": ["Natural Law", "aquinas"],
    "aquinas-five-ways": ["The Five Ways", "aquinas"],
    "aquinas-double-effect": ["Doctrine of Double Effect", "aquinas"],
    "aquinas-virtues": ["Cardinal and Theological Virtues", "aquinas"],
    "ockham-razor": ["Ockham's Razor", "ockham"],
    "avicenna-floating-man": ["The Floating Man", "avicenna"],
    "averroes-reason-revelation": ["Concord of Reason and Revelation", "averroes"],
    "descartes-cogito": ["The Cogito", "descartes"],
    "cartesian-doubt": ["Methodological Doubt (evil demon)", "descartes"],
    "cartesian-dualism": ["Mind–Body Dualism", "descartes"],
    "spinoza-monism": ["Substance Monism (Deus sive Natura)", "spinoza"],
    "spinoza-conatus": ["Conatus (striving to persist)", "spinoza"],
    "spinoza-determinism": ["Spinozist Necessity", "spinoza"],
    "best-possible-world": ["The Best of All Possible Worlds", "leibniz"],
    "monadology": ["Monadology", "leibniz"],
    "sufficient-reason": ["Principle of Sufficient Reason", "leibniz"],
    "pascals-wager": ["Pascal's Wager", "pascal"],
    "montaigne-skepticism": ["Que sais-je? (Montaigne's skepticism)", "montaigne"],
    "locke-personal-identity": ["Personal Identity (memory theory)", "locke"],
    "tabula-rasa": ["Tabula Rasa", "locke"],
    "locke-natural-rights": ["Natural Rights", "locke"],
    "locke-labor-property": ["Labor Theory of Property", "locke"],
    "berkeley-idealism": ["Subjective Idealism (esse est percipi)", "berkeley"],
    "hume-is-ought": ["Is–Ought Problem", "hume"],
    "hume-induction": ["Problem of Induction", "hume"],
    "hume-bundle": ["Bundle Theory of Self", "hume"],
    "hume-sentimentalism": ["Reason Is the Slave of the Passions", "hume"],
    "hume-miracles": ["On Miracles", "hume"],
    "reid-common-sense": ["Common Sense Philosophy", "reid"],
    # kant-german-idealism
    "categorical-imperative": ["The Categorical Imperative", "kant"],
    "kant-humanity-formula": ["Humanity as an End in Itself", "kant"],
    "kant-autonomy": ["Autonomy of the Will", "kant"],
    "kingdom-of-ends": ["Kingdom of Ends", "kant"],
    "kant-phenomena-noumena": ["Phenomena and Noumena", "kant"],
    "transcendental-idealism": ["Transcendental Idealism", "kant"],
    "kant-aesthetics": ["Judgment of Taste and the Sublime", "kant"],
    "kant-perpetual-peace": ["Perpetual Peace", "kant"],
    "kant-respect": ["Respect for Persons", "kant"],
    "hegel-dialectic": ["The Dialectic", "hegel"],
    "hegel-master-slave": ["Master–Slave Dialectic", "hegel"],
    "hegel-geist": ["Geist (World Spirit)", "hegel"],
    "hegel-history": ["History Has a Direction", "hegel"],
    "hegel-recognition": ["Struggle for Recognition", "hegel"],
    "schopenhauer-will": ["The World as Will", "schopenhauer"],
    "schopenhauer-pessimism": ["Philosophical Pessimism", "schopenhauer"],
    "schopenhauer-compassion": ["Ethics of Compassion", "schopenhauer"],
    "schopenhauer-pendulum": ["Pendulum Between Pain and Boredom", "schopenhauer"],
    # nineteenth-century
    "will-to-power": ["Will to Power", "nietzsche"],
    "ubermensch": ["The Übermensch", "nietzsche"],
    "eternal-recurrence": ["Eternal Recurrence", "nietzsche"],
    "amor-fati": ["Amor Fati (love of fate)", "nietzsche"],
    "master-slave-morality": ["Master and Slave Morality", "nietzsche"],
    "death-of-god": ["The Death of God", "nietzsche"],
    "nietzsche-perspectivism": ["Perspectivism", "nietzsche"],
    "apollonian-dionysian": ["The Apollonian and the Dionysian", "nietzsche"],
    "ressentiment": ["Ressentiment", "nietzsche"],
    "last-man": ["The Last Man", "nietzsche"],
    "marx-alienation": ["Alienation", "marx"],
    "commodity-fetishism": ["Commodity Fetishism", "marx"],
    "historical-materialism": ["Historical Materialism", "marx"],
    "class-struggle": ["Class Struggle", "marx"],
    "marx-ideology": ["Ideology and False Consciousness", "marx"],
    "social-darwinism": ["Social Darwinism", "spencer"],
    # utilitarian-consequentialist
    "utilitarianism": ["Utilitarianism", "", "utilitarian-consequentialist"],
    "hedonic-calculus": ["The Hedonic Calculus", "bentham"],
    "greatest-happiness": ["The Greatest Happiness Principle", "mill"],
    "higher-lower-pleasures": ["Higher and Lower Pleasures", "mill"],
    "harm-principle": ["The Harm Principle", "mill"],
    "mill-liberty": ["On Liberty", "mill"],
    "mill-subjection-women": ["The Subjection of Women", "mill"],
    "animal-liberation": ["Animal Liberation", "singer"],
    "speciesism": ["Speciesism", "singer"],
    "drowning-child": ["The Drowning Child (obligation to aid)", "singer"],
    "consequentialism": ["Consequentialism", "", "utilitarian-consequentialist"],
    # existentialism-phenomenology
    "existentialism": ["Existentialism", "", "existentialism-phenomenology"],
    "leap-of-faith": ["The Leap of Faith", "kierkegaard"],
    "kierkegaard-stages": ["The Stages on Life's Way", "kierkegaard"],
    "kierkegaard-despair": ["Despair (sickness unto death)", "kierkegaard"],
    "kierkegaard-anxiety": ["Anxiety (the dizziness of freedom)", "kierkegaard"],
    "teleological-suspension": ["Teleological Suspension of the Ethical", "kierkegaard"],
    "subjective-truth": ["Subjectivity Is Truth", "kierkegaard"],
    "intentionality": ["Intentionality", "husserl"],
    "phenomenology": ["Phenomenology", "", "existentialism-phenomenology"],
    "dasein": ["Dasein (being-there)", "heidegger"],
    "being-toward-death": ["Being-Toward-Death", "heidegger"],
    "authenticity": ["Authenticity", "heidegger"],
    "thrownness": ["Thrownness (Geworfenheit)", "heidegger"],
    "das-man": ["The They-Self (das Man)", "heidegger"],
    "heidegger-technology": ["The Question Concerning Technology", "heidegger"],
    "existence-precedes-essence": ["Existence Precedes Essence", "sartre"],
    "bad-faith": ["Bad Faith", "sartre"],
    "sartre-freedom": ["Radical Freedom and Responsibility", "sartre"],
    "the-look": ["The Look (hell is other people)", "sartre"],
    "woman-as-other": ["Woman as the Other", "beauvoir"],
    "ethics-of-ambiguity": ["The Ethics of Ambiguity", "beauvoir"],
    "becoming-woman": ["One Is Not Born a Woman", "beauvoir"],
    "the-absurd": ["The Absurd", "camus"],
    "sisyphus": ["The Myth of Sisyphus", "camus"],
    "camus-revolt": ["Rebellion and Revolt", "camus"],
    "embodiment": ["Embodiment (the lived body)", "merleau-ponty"],
    "frankl-meaning": ["Man's Search for Meaning (logotherapy)", "frankl"],
    "levinas-face": ["The Face of the Other", "levinas"],
    # mind-language-metaphysics
    "turing-test": ["The Turing Test", "turing"],
    "chinese-room": ["The Chinese Room", "searle"],
    "searle-intentionality": ["Biological Naturalism / Intentionality", "searle"],
    "brain-in-a-vat": ["Brain in a Vat", "putnam"],
    "twin-earth": ["Twin Earth (semantic externalism)", "putnam"],
    "hard-problem": ["The Hard Problem of Consciousness", "chalmers"],
    "philosophical-zombies": ["Philosophical Zombies", "chalmers"],
    "extended-mind": ["The Extended Mind", "clark"],
    "intentional-stance": ["The Intentional Stance", "dennett"],
    "cartesian-theater": ["The Cartesian Theater (critique)", "dennett"],
    "language-games": ["Language Games", "wittgenstein"],
    "private-language": ["The Private Language Argument", "wittgenstein"],
    "russells-teapot": ["Russell's Teapot", "russell"],
    "naturalistic-fallacy": ["The Naturalistic Fallacy", "moore"],
    "sense-reference": ["Sense and Reference", "frege"],
    "quine-indeterminacy": ["Indeterminacy of Translation", "quine"],
    "web-of-belief": ["The Web of Belief", "quine"],
    "kripke-naming": ["Naming and Necessity (rigid designators)", "kripke"],
    "possible-worlds": ["Possible Worlds", "lewis"],
    "category-mistake": ["Category Mistake", "ryle"],
    "ghost-in-the-machine": ["The Ghost in the Machine", "ryle"],
    "knowledge-argument": ["The Knowledge Argument (Mary's Room)", "jackson"],
    "what-is-it-like": ["What Is It Like to Be a Bat?", "nagel"],
    "parfit-teleportation": ["Teleporter Paradox (personal fission)", "parfit"],
    "a-series-time": ["The A-Series and B-Series of Time", "mctaggart"],
    "free-will-determinism": ["Free Will vs Determinism", "", "mind-language-metaphysics"],
    "compatibilism": ["Compatibilism", "", "mind-language-metaphysics"],
    "personal-identity": ["Personal Identity", "", "mind-language-metaphysics"],
    "ship-of-theseus-mind": ["—", "", "mind-language-metaphysics"],
    "simulation-hypothesis": ["The Simulation Hypothesis", "bostrom"],
    "time-travel": ["The Metaphysics of Time Travel", "", "mind-language-metaphysics"],
    "bergson-duration": ["Duration (durée)", "bergson"],
    "bergson-elan-vital": ["Élan Vital (creative evolution)", "bergson"],
    "bergson-memory": ["Matter and Memory", "bergson"],
    "bergson-laughter": ["Laughter (the comic as mechanical encrusted on the living)", "bergson"],
    "freud-unconscious": ["The Unconscious", "freud"],
    "freud-death-drive": ["The Death Drive (Thanatos)", "freud"],
    "freud-civilization": ["Civilization and Its Discontents", "freud"],
    "jung-archetypes": ["Archetypes", "jung"],
    "jung-collective-unconscious": ["The Collective Unconscious", "jung"],
    "jung-shadow": ["The Shadow", "jung"],
    "lacan-mirror-stage": ["The Mirror Stage", "lacan"],
    "lacan-symbolic": ["The Symbolic, the Imaginary and the Real", "lacan"],
    "berlin-two-liberties": ["Two Concepts of Liberty", "isaiah-berlin"],
    "gadamer-hermeneutics": ["Philosophical Hermeneutics (fusion of horizons)", "gadamer"],
    # knowledge-science-reality
    "gettier-problem": ["The Gettier Problem", "gettier"],
    "reliabilism": ["Reliabilism", "goldman"],
    "paradigm-shift": ["Paradigm Shifts", "kuhn"],
    "falsification": ["Falsificationism", "popper"],
    "open-society": ["The Open Society", "popper"],
    "epistemological-anarchism": ["Anything Goes (epistemological anarchism)", "feyerabend"],
    "bacon-idols": ["The Idols of the Mind", "bacon"],
    "existence-risk": ["Existential Risk", "bostrom"],
    "skepticism": ["Philosophical Skepticism", "", "knowledge-science-reality"],
    "scientific-realism": ["Scientific Realism vs Anti-Realism", "", "knowledge-science-reality"],
    # ethics-moral-psychology
    "trolley-problem": ["The Trolley Problem", "foot"],
    "thomson-violinist": ["The Violinist Argument", "thomson"],
    "moral-luck": ["Moral Luck", "williams"],
    "williams-integrity": ["Integrity Against Utilitarianism", "williams"],
    "second-order-desires": ["Second-Order Desires (personhood)", "frankfurt"],
    "frankfurt-bullshit": ["On Bullshit", "frankfurt"],
    "korsgaard-constructivism": ["Kantian Constructivism", "korsgaard"],
    "care-ethics": ["The Ethics of Care", "gilligan"],
    "care-ethics-noddings": ["Caring as the Ground of Ethics", "noddings"],
    "macintyre-tradition": ["Virtues, Practices and Traditions", "macintyre"],
    "capabilities-approach": ["The Capabilities Approach", "nussbaum"],
    "modern-moral-philosophy": ["Anscombe's 'Modern Moral Philosophy'", "anscombe"],
    "invisible-hand": ["The Invisible Hand", "adam-smith"],
    "impartial-spectator": ["The Impartial Spectator", "adam-smith"],
    "wolf-meaning": ["Meaning in Life", "wolf"],
    "golden-rule": ["The Golden Rule", "", "ethics-moral-psychology"],
    "moral-relativism": ["Moral Relativism", "", "ethics-moral-psychology"],
    "moral-egoism": ["Ethical Egoism", "", "ethics-moral-psychology"],
    "punishment-theory": ["Punishment: Retribution vs Rehabilitation", "", "ethics-moral-psychology"],
    "just-war-theory": ["Just War Theory", "", "ethics-moral-psychology"],
    "philosophy-of-love": ["Philosophy of Love", "", "ethics-moral-psychology"],
    "forgiveness": ["Forgiveness", "", "ethics-moral-psychology"],
    "deontology": ["Deontology", "", "ethics-moral-psychology"],
    "virtue-ethics": ["Virtue Ethics", "", "ethics-moral-psychology"],
    "moral-psychology": ["Moral Psychology (character, vice, weakness of will)", "", "ethics-moral-psychology"],
    "applied-ethics": ["Applied Ethics (bioethics, technology, AI)", "", "ethics-moral-psychology"],
    # political-social
    "state-of-nature": ["The State of Nature", "hobbes"],
    "social-contract": ["The Social Contract", "hobbes"],
    "rousseau-social-contract": ["The General Will", "rousseau"],
    "rousseau-natural-goodness": ["Natural Goodness and Corruption by Society", "rousseau"],
    "machiavelli-virtu": ["Virtù and Fortuna", "machiavelli"],
    "machiavelli-ends": ["The Ends Justify the Means", "machiavelli"],
    "veil-of-ignorance": ["The Veil of Ignorance", "rawls"],
    "justice-as-fairness": ["Justice as Fairness", "rawls"],
    "difference-principle": ["The Difference Principle", "rawls"],
    "experience-machine": ["The Experience Machine", "nozick"],
    "minimal-state": ["The Minimal State", "nozick"],
    "communitarianism": ["Communitarianism", "sandel"],
    "banality-of-evil": ["The Banality of Evil", "arendt"],
    "arendt-totalitarianism": ["Totalitarianism", "arendt"],
    "panopticon": ["The Panopticon (surveillance)", "foucault"],
    "power-knowledge": ["Power/Knowledge", "foucault"],
    "discipline": ["Discipline and Docile Bodies", "foucault"],
    "deconstruction": ["Deconstruction", "derrida"],
    "binary-oppositions": ["Binary Oppositions", "derrida"],
    "rhizome": ["The Rhizome", "deleuze"],
    "simulacra": ["Simulacra and Simulation (the hyperreal)", "baudrillard"],
    "grand-narratives": ["The End of Grand Narratives", "lyotard"],
    "hegemony": ["Cultural Hegemony", "gramsci"],
    "one-dimensional-man": ["One-Dimensional Man", "marcuse"],
    "culture-industry": ["The Culture Industry", "adorno"],
    "benjamin-aura": ["The Aura of the Artwork", "benjamin"],
    "public-sphere": ["The Public Sphere", "habermas"],
    "anarchism": ["Anarchism", "", "political-social"],
    "utopia-dystopia": ["Utopia and Dystopia", "", "political-social"],
    "democracy-theory": ["Democracy", "", "political-social"],
    "terrorism-violence": ["The Ethics of Political Violence", "", "political-social"],
    # pragmatism-american
    "pragmatism": ["Pragmatism", "", "pragmatism-american"],
    "pragmatic-method": ["The Pragmatic Method", "peirce"],
    "will-to-believe": ["The Will to Believe", "william-james"],
    "stream-of-consciousness": ["Stream of Consciousness", "william-james"],
    "pragmatic-truth": ["Truth as What Works", "william-james"],
    "dewey-democracy": ["Democracy as a Way of Life", "dewey"],
    "dewey-experience": ["Experience and Education", "dewey"],
    "emerson-self-reliance": ["Self-Reliance", "emerson"],
    "transcendentalism": ["Transcendentalism", "", "pragmatism-american"],
    "thoreau-walden": ["Walden (deliberate living)", "thoreau"],
    "civil-disobedience": ["Civil Disobedience", "thoreau"],
    "addams-settlement": ["Social Ethics of the Settlement House", "addams"],
    # feminism-gender-race
    "feminism": ["Feminism", "", "feminism-gender-race"],
    "vindication-women": ["A Vindication of the Rights of Woman", "wollstonecraft"],
    "feminine-mystique": ["The Feminine Mystique (the problem with no name)", "friedan"],
    "dialectic-of-sex": ["The Dialectic of Sex", "firestone"],
    "gender-performativity": ["Gender Performativity", "butler"],
    "heteronormativity": ["Heteronormativity", "butler"],
    "mackinnon-dominance": ["Dominance Approach (pornography and gender)", "mackinnon"],
    "birdcage-oppression": ["Oppression as a Birdcage", "frye"],
    "five-faces-oppression": ["Five Faces of Oppression", "young"],
    "intersectionality": ["Intersectionality", "crenshaw"],
    "double-consciousness": ["Double Consciousness", "dubois"],
    "racial-contract": ["The Racial Contract", "mills"],
    "black-skin-white-masks": ["Black Skin, White Masks", "fanon"],
    "cosmopolitanism-ethics": ["Cosmopolitanism", "appiah"],
    "epistemic-injustice": ["Epistemic Injustice", "fricker"],
    "objectification": ["Objectification", "", "feminism-gender-race"],
    "disability-philosophy": ["Philosophy of Disability", "", "feminism-gender-race"],
    "male-gaze": ["The Male Gaze", "", "feminism-gender-race"],
    # environment-animal
    "land-ethic": ["The Land Ethic", "leopold"],
    "deep-ecology": ["Deep Ecology", "naess"],
    "ecofeminism": ["Ecofeminism", "plumwood"],
    "animal-rights": ["Animal Rights (subjects-of-a-life)", "regan"],
    "climate-ethics": ["Climate Ethics", "", "environment-animal"],
    "anthropocentrism": ["Anthropocentrism", "", "environment-animal"],
    "food-ethics": ["Food Ethics", "", "environment-animal"],
    "wilderness-ethics": ["Wilderness and Nature Aesthetics", "", "environment-animal"],
    # religion-meaning
    "watchmaker-argument": ["The Watchmaker Argument (design)", "paley"],
    "problem-of-evil": ["The Problem of Evil", "", "religion-meaning"],
    "faith-vs-reason": ["Faith and Reason", "", "religion-meaning"],
    "meaning-of-life": ["The Meaning of Life", "", "religion-meaning"],
    "immortality": ["Immortality and the Soul", "", "religion-meaning"],
    "i-thou": ["I–Thou Relation", "buber"],
    "tillich-ground-of-being": ["God as the Ground of Being", "tillich"],
    "plantinga-basic-beliefs": ["Properly Basic Belief", "plantinga"],
    "fate-vs-free-will": ["Fate and Foreknowledge", "", "religion-meaning"],
    # hole-driven extensions (final aggregation, 2026-09-28): 79 concepts
    "paradox-of-fiction": ["The Paradox of Fiction", "", "mind-language-metaphysics"],
    "catharsis": ["Catharsis (tragic purgation)", "aristotle"],
    "narrative-identity": ["Narrative Identity", "", "mind-language-metaphysics"],
    "supererogation": ["Supererogation (beyond the call of duty)", "", "ethics-moral-psychology"],
    "transhumanism": ["Transhumanism", "", "ethics-moral-psychology"],
    "nihilism": ["Nihilism", "", "nineteenth-century"],
    "informal-fallacies": ["Informal Fallacies", "", "knowledge-science-reality"],
    "functionalism": ["Functionalism (philosophy of mind)", "", "mind-language-metaphysics"],
    "family-resemblance": ["Family Resemblance", "wittgenstein"],
    "scientism": ["Scientism", "", "knowledge-science-reality"],
    "posthumanism": ["Posthumanism", "", "mind-language-metaphysics"],
    "game-theory": ["Game Theory", "", "political-social"],
    "problem-of-other-minds": ["The Problem of Other Minds", "", "mind-language-metaphysics"],
    "mimesis": ["Mimesis (art as imitation)", "aristotle"],
    "gnosticism": ["Gnosticism (gnosis)", "", "religion-meaning"],
    "dirty-hands": ["The Problem of Dirty Hands", "", "political-social"],
    "religious-pluralism": ["Religious Pluralism", "john-hick"],
    "the-uncanny": ["The Uncanny (das Unheimliche)", "freud"],
    "bushido": ["Bushido (the way of the warrior)", "", "eastern-world"],
    "logical-positivism": ["Logical Positivism (verifiability theory)", "", "knowledge-science-reality"],
    "truth-in-fiction": ["Truth in Fiction", "kendall-walton"],
    "memetics": ["Memetics (cultural evolution)", "", "knowledge-science-reality"],
    "ethics-of-belief": ["The Ethics of Belief (evidentialism)", "clifford"],
    "philosophy-of-play": ["Philosophy of Play", "huizinga"],
    "corporate-personhood": ["Corporate Moral Personhood", "", "political-social"],
    "moral-particularism": ["Moral Particularism", "", "ethics-moral-psychology"],
    "relational-autonomy": ["Relational Autonomy", "", "feminism-gender-race"],
    "philosophy-of-humor": ["Philosophy of Humor", "", "ethics-moral-psychology"],
    "eliminative-materialism": ["Eliminative Materialism", "", "mind-language-metaphysics"],
    "fascism": ["Fascism", "", "political-social"],
    "incongruity-theory-humor": ["Incongruity Theory of Humor", "kant"],
    "personalism": ["Personalism", "", "ethics-moral-psychology"],
    "standard-of-taste": ["The Standard of Taste", "hume"],
    "abduction": ["Inference to the Best Explanation (abduction)", "", "pragmatism-american"],
    "prisoners-dilemma": ["The Prisoner's Dilemma and Tit-for-Tat", "", "political-social"],
    "maslow-hierarchy-of-needs": ["Maslow's Hierarchy of Needs", "", "ethics-moral-psychology"],
    "underdetermination": ["Underdetermination of Theory by Evidence", "", "knowledge-science-reality"],
    "the-sublime": ["The Sublime", "", "kant-german-idealism"],
    "correspondence-theory-of-truth": ["Correspondence Theory of Truth", "", "knowledge-science-reality"],
    "tragedy-of-the-commons": ["The Tragedy of the Commons", "", "political-social"],
    "personhood": ["Personhood (vs genetic humanity)", "", "ethics-moral-psychology"],
    "imaginative-resistance": ["Imaginative Resistance", "", "mind-language-metaphysics"],
    "art-horror": ["Art-Horror", "carroll-aesthetics"],
    "great-chain-of-being": ["The Great Chain of Being", "", "medieval-early-modern"],
    "oedipus-complex": ["The Oedipus Complex", "freud"],
    "legal-positivism": ["Legal Positivism (law and morality separable)", "", "political-social"],
    "self-deception": ["Self-Deception", "", "ethics-moral-psychology"],
    "constitutive-rules": ["Constitutive Rules (rules that define games)", "", "mind-language-metaphysics"],
    "argument-from-reason": ["The Argument from Reason", "cs-lewis"],
    "metabolic-rift": ["Metabolic Rift", "marx"],
    "epistemology-of-testimony": ["Epistemology of Testimony", "", "knowledge-science-reality"],
    "institutional-theory-of-art": ["Institutional Theory of Art", "", "mind-language-metaphysics"],
    "natural-kinds": ["Natural Kinds vs Nominal Kinds", "", "knowledge-science-reality"],
    "situationism": ["Situationism (situationist social psychology)", "", "ethics-moral-psychology"],
    "soul-making-theodicy": ["Soul-Making Theodicy", "john-hick"],
    "cyborg": ["The Cyborg", "haraway"],
    "purity-and-danger": ["Purity and Danger (dirt as matter out of place)", "", "political-social"],
    "eugenics": ["Eugenics", "", "ethics-moral-psychology"],
    "liar-paradox": ["The Liar Paradox", "", "mind-language-metaphysics"],
    "dialetheism": ["Dialetheism (true contradictions)", "graham-priest"],
    "romanticism": ["Romanticism (imagination and the infinite)", "", "nineteenth-century"],
    "abjection": ["Abjection (the abject)", "kristeva"],
    "philosophy-of-music": ["Philosophy of Music", "", "kant-german-idealism"],
    "aestheticism": ["Aestheticism (art for art's sake)", "", "nineteenth-century"],
    "political-realism": ["Political Realism (power over morality)", "carl-schmitt"],
    "anti-natalism": ["Anti-Natalism", "benatar"],
    "ethics-of-lying": ["The Ethics of Lying and Deception", "", "ethics-moral-psychology"],
    "physicalism": ["Physicalism", "", "mind-language-metaphysics"],
    "moral-dilemmas": ["Moral Dilemmas (non-negotiable duties)", "", "ethics-moral-psychology"],
    "philosophy-of-art": ["Philosophy of Art (artistic value)", "", "kant-german-idealism"],
    "biopower": ["Biopower", "foucault"],
    "uncanny-valley": ["The Uncanny Valley", "", "mind-language-metaphysics"],
    "society-of-the-spectacle": ["The Society of the Spectacle", "guy-debord"],
    "aspect-perception": ["Aspect Perception (seeing-as)", "wittgenstein"],
    "stakeholder-theory": ["Stakeholder Theory (vs stockholder theory)", "", "ethics-moral-psychology"],
    "death-of-the-author": ["The Death of the Author", "roland-barthes"],
    "pacifism": ["Pacifism", "", "political-social"],
    "film-as-philosophy": ["Film as Philosophy", "", "knowledge-science-reality"],
    "ontology-of-fiction": ["Ontology of Fictional Characters", "", "mind-language-metaphysics"],
    # 2026-10-03 extension: holes from the 6 newly recovered books (u439-u449)
    "darshana": ["Darshana (systematic 'view' or school)", "", "eastern-world"],
    "vedic-sacrifice": ["Vedic Sacrifice (yajna)", "", "eastern-world"],
    "dependent-origination": ["Dependent Origination (pratityasamutpada)", "", "eastern-world"],
    "abhidharma": ["Abhidharma (dharma analysis)", "", "eastern-world"],
    "yogacara-mind-only": ["Yogacara 'Mind-Only' (cittamatra)", "", "eastern-world"],
    "classical-yoga": ["Classical Yoga (Patanjali)", "", "eastern-world"],
    "samkhya-dualism": ["Samkhya Dualism (purusha and prakriti)", "", "eastern-world"],
    "vaisheshika-categories": ["Vaisheshika Categories (padartha)", "", "eastern-world"],
    "nyaya-five-limb-inference": ["Nyaya Five-Membered Inference", "", "eastern-world"],
    "mimamsa": ["Mimamsa (Vedic exegesis)", "", "eastern-world"],
    "semiotics-signifier-signified": ["Semiotics (signifier and signified)", "", "mind-language-metaphysics"],
    "anti-psychologism": ["Anti-Psychologism", "", "mind-language-metaphysics"],
    "intrinsic-vs-instrumental-value": ["Intrinsic vs Instrumental Value", "", "ethics-moral-psychology"],
    "sorites-paradox": ["Sorites Paradox (vagueness)", "", "mind-language-metaphysics"],
    "maternal-thinking": ["Maternal Thinking (Sara Ruddick)", "", "feminism-gender-race"],
    "original-sin": ["Original Sin", "", "religion-meaning"],
    "parasocial-relationship": ["Parasocial Relationships", "", "ethics-moral-psychology"],
    "reputation": ["Reputation (social epistemology of)", "", "knowledge-science-reality"],
    "repetition-and-difference": ["Repetition and Difference (Deleuze)", "deleuze"],
    "archive-fever": ["Archive Fever (Derrida)", "", "mind-language-metaphysics"],
    "philosophy-of-grief": ["Philosophy of Grief", "", "ethics-moral-psychology"],
    "affective-injustice": ["Affective Injustice", "", "feminism-gender-race"],
    "philosophy-of-anger": ["Philosophy of Anger", "", "ethics-moral-psychology"],
    "standpoint-epistemology": ["Feminist Standpoint Epistemology", "", "feminism-gender-race"],
    "beauty-myth": ["The Beauty Myth (Naomi Wolf)", "", "feminism-gender-race"],
    "reproductive-justice": ["Reproductive Justice", "", "feminism-gender-race"],
    "race-as-social-construct": ["Race as Social Construct", "", "feminism-gender-race"],
    "wrongful-discrimination": ["Wrongful Discrimination", "", "feminism-gender-race"],
    "speech-acts": ["Speech Acts (performative utterances)", "", "mind-language-metaphysics"],
    "mimetic-desire": ["Mimetic Desire (Girard)", "girard"],
    "scapegoat-mechanism": ["Scapegoat Mechanism (Girard)", "girard"],
    "becoming-other": ["Becoming-Other (Deleuzian becoming)", "deleuze"],
    "open-interpretation": ["Open Interpretation (multiple valid readings)", "", "mind-language-metaphysics"],
    "popular-parody": ["Popular Parody (homage vs art parody)", "linda-hutcheon", "kant-german-idealism"],
}


def main():
    missing = []
    concepts = {}
    for slug, (name, phil, *rest) in C.items():
        if name == "—":
            continue
        if phil:
            if phil not in P:
                missing.append(slug)
                continue
            concepts[slug] = {"n": name, "p": phil, "dom": P[phil][2]}
        else:
            dom = rest[0] if rest else None
            if dom not in DOMAINS:
                missing.append(slug)
                continue
            concepts[slug] = {"n": name, "p": "", "dom": dom}
    by_domain = {}
    for slug, c in concepts.items():
        by_domain.setdefault(c["dom"], []).append(slug)
    tax = {
        "domains": {k: {"n": v} for k, v in DOMAINS.items()},
        "philosophers": {k: {"n": v[0], "d": v[1], "dom": v[2]}
                         for k, v in P.items()},
        "concepts": concepts,
    }
    OUT.write_text(json.dumps(tax, indent=1, ensure_ascii=False), encoding="utf-8")
    n_phil_by_dom = {}
    for k, v in P.items():
        n_phil_by_dom[v[2]] = n_phil_by_dom.get(v[2], 0) + 1
    print("philosophers:", len(P), " concepts:", len(concepts), " domains:", len(DOMAINS))
    for d, slugs in by_domain.items():
        print("  %-28s %3d concepts  %2d philosophers"
              % (d, len(slugs), n_phil_by_dom.get(d, 0)))
    if missing:
        print("MISSING refs:", missing)


if __name__ == "__main__":
    main()
